word_embedding_size : 100
charlstm_output_size: 512
char_embedding_size : 64
encoder_dropout     : 0.3
mlp_input           : 400
mlp_tag_hidden      : 30
mlp_arc_hidden      : 500
mlp_lab_hidden      : 100
mlp_dropout         : 0.3
word_dropout        : 0.3
batch_size          : 2
epochs              : 70
lr                  : 0.001
lexer               : 'default'
device              : 'cpu'
