# For use with scripts/train_models.py
trains:
  # Train groups define a matrix of training config×training treebanks.
  - group: fr
    configs:
      - "camembert.yaml"
      - "flaubert.yaml"
      - "mdeberta.yaml"
      - "xlm-r-base.yaml"
    treebanks:
      - "UD_French-GSD"
      - "UD_French-Sequoia"
      - "UD_French-ALL"

evals:
  # Evals list the treebanks used to evaluate the models trained for each train group.
  fr:
    - "UD_French-GSD"
    - "UD_French-ParisStories"
    - "UD_French-Rhapsodie"
    - "UD_French-Sequoia"
    - "UD_French-ALL"
